name: eslint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run ESLint
        run: |
          npm run eslint
          working-directory = ./
